### ISSUE TITLE
Visualizzazione libri

### ISSUE THREAD

**Issue by francesconero** [Middleware-Technologies/RottenBooks#2]
Come implementiamo la visualizzazione dei libri? Per ora (0a3e2062bc626bd1c28054ce0d31f2a491833a5b) sono un array "books" nell'oggetto films, e io ne stampo il numero trovato in una colonna.

**Comment by paolomanca** [comment]
I libri ora vengono visualizzati come lista di titolo e link, vogliamo metterci anche l'immagine? Io ho un po' paura che occupi un sacco di spazio per nulla.

**Comment by francesconero** [comment]
Concordo, meglio solo link, titolo e magari autore?

**Comment by paolomanca** [comment]
Okay, vedo se c'è modo di inserirlo senza diventare illeggibile.

**Comment by francesconero** [comment]
Mi sembra di non averlo aggiunto al model di Book, quindi dovrai fare anche quello.

**Comment by paolomanca** [comment]
Ti licenzio, sai

**Comment by francesconero** [comment]
No Vi prego, Onorevolissimo!
![Pietà](http://www.palermomania.it/public/news/fantozzi.jpg)

**Comment by ghost** [comment]
link e titolo sono più che sufficienti secondo me...
